// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let urlDB;

if (process.env.NODE_ENV === "TEST") {
    urlDB = `${process.env.TEST_DATABASE_URL}`;
} else {
    urlDB = `${process.env.DATABASE_URL}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed/seed.js"
  },
  datasource: {
    url: urlDB,
  },
});
