// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const { defineConfig } = require("prisma/config");

let urlDB;

if (process.env.NODE_ENV === "PROD") {
    urlDB = `${process.env.DATABASE_URL}`;
} else {
    urlDB = `${process.env.TEST_DATABASE_URL}`;
}

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed/seed.js"
  },
  datasource: {
    url: urlDB,
  },
});
